// This file was generated by counterfeiter
package fakes

import "sync"

type UAAClientService struct {
	GetTokenStub        func() (string, error)
	getTokenMutex       sync.RWMutex
	getTokenArgsForCall []struct{}
	getTokenReturns     struct {
		result1 string
		result2 error
	}
}

func (fake *UAAClientService) GetToken() (string, error) {
	fake.getTokenMutex.Lock()
	fake.getTokenArgsForCall = append(fake.getTokenArgsForCall, struct{}{})
	fake.getTokenMutex.Unlock()
	if fake.GetTokenStub != nil {
		return fake.GetTokenStub()
	} else {
		return fake.getTokenReturns.result1, fake.getTokenReturns.result2
	}
}

func (fake *UAAClientService) GetTokenCallCount() int {
	fake.getTokenMutex.RLock()
	defer fake.getTokenMutex.RUnlock()
	return len(fake.getTokenArgsForCall)
}

func (fake *UAAClientService) GetTokenReturns(result1 string, result2 error) {
	fake.GetTokenStub = nil
	fake.getTokenReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}
