// This file was generated by counterfeiter
package fakes

import "sync"

type WarrantClient struct {
	GetTokenStub        func(user string, secret string) (string, error)
	getTokenMutex       sync.RWMutex
	getTokenArgsForCall []struct {
		user   string
		secret string
	}
	getTokenReturns struct {
		result1 string
		result2 error
	}
}

func (fake *WarrantClient) GetToken(user string, secret string) (string, error) {
	fake.getTokenMutex.Lock()
	fake.getTokenArgsForCall = append(fake.getTokenArgsForCall, struct {
		user   string
		secret string
	}{user, secret})
	fake.getTokenMutex.Unlock()
	if fake.GetTokenStub != nil {
		return fake.GetTokenStub(user, secret)
	} else {
		return fake.getTokenReturns.result1, fake.getTokenReturns.result2
	}
}

func (fake *WarrantClient) GetTokenCallCount() int {
	fake.getTokenMutex.RLock()
	defer fake.getTokenMutex.RUnlock()
	return len(fake.getTokenArgsForCall)
}

func (fake *WarrantClient) GetTokenArgsForCall(i int) (string, string) {
	fake.getTokenMutex.RLock()
	defer fake.getTokenMutex.RUnlock()
	return fake.getTokenArgsForCall[i].user, fake.getTokenArgsForCall[i].secret
}

func (fake *WarrantClient) GetTokenReturns(result1 string, result2 error) {
	fake.GetTokenStub = nil
	fake.getTokenReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}
